# name: NPM Version Manager

# on:
#   push:
#     branches:
#       - main

# jobs:
#   version:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#         with:
#           token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
#       - run: git config --global user.name '${{ secrets.GH_PUBLIC_NAME }}'
#       - run: git config --global user.email '${{ secrets.GH_EMAIL }}'
#       - run: npm version patch 
#       - run: git push